from itertools import combinations
import random
number = list('0123456789')
sample = input('Please enter the specified random number table (if it is directly generated by the system, enter directly):')
if not sample:
    sample = ''.join([str(random.randint(0,9)) for _ in range(100)])
print(sample)

sjn = input('Please enter the number of random digits to be calculated, separated by spaces:').split()
sjn = list(map(int,sjn))
for ii in sjn:
    print(f'Current random {ii} bit results:')
    com = [list(i) for i in combinations(number,ii)]
    forget_res = [0 for _ in range(100)]
    forget_max_cr = [0,[]]
    forget_max_all = [0,[]]
    for c in com:
        flag = 0
        aw_sample = sample[::]
        for i in c:
            aw_sample = aw_sample.replace(i,'A')
        cr_max = 0
        for i in aw_sample[::-1]:
            if i == 'A':
                cr_max += 1
            else:
                break
        if cr_max > forget_max_cr[0]:
            forget_max_cr = [cr_max,[''.join(c)]]
        elif cr_max == forget_max_cr[0]:
            forget_max_cr[1].append(''.join(c))
        for t in range(99,-1,-1):
            ti = aw_sample.count('A'*t)
            if ti != 0:
                forget_res[t] += ti
                flag = t
                break
        if flag > forget_max_all[0]:
            forget_max_all = [flag,[''.join(c)]]
        elif flag == forget_max_all[0]:
            forget_max_all[1].append(''.join(c))
    for i in range(len(forget_res)):
        if forget_res[i]:
            print(f'Any {ii} number appears continuously',i,'times:',forget_res[i])
    print('The current maximum number of consecutive occurrences is:',forget_max_cr[0],'[',','.join(forget_max_cr[1]),']')
    print('The maximum number of global consecutive occurrences is:',forget_max_all[0],'[',','.join(forget_max_all[1]),']')


    forget_res = [0 for _ in range(100)]
    forget_max_cr = [0,[]]
    forget_max_all = [0,[]]
    for c in com:
        flag = 0
        aw_sample = ''.join([i if i in c else 'A' for i in sample])
        cr_max = 0
        for i in aw_sample[::-1]:
            if i == 'A':
                cr_max += 1
            else:
                break
        if cr_max > forget_max_cr[0]:
            forget_max_cr = [cr_max,[''.join(c)]]
        elif cr_max == forget_max_cr[0]:
            forget_max_cr[1].append(''.join(c))
        for t in range(99,-1,-1):
            ti = aw_sample.count('A'*t)
            if ti != 0:
                forget_res[t] += ti
                flag = t
                break
        if flag > forget_max_all[0]:
            forget_max_all = [flag,[''.join(c)]]
        elif flag == forget_max_all[0]:
            forget_max_all[1].append(''.join(c))
    for i in range(len(forget_res)):
        if forget_res[i]:
            print(f'Any {ii} number is continuously omitted:',i,'times:',forget_res[i])
    print('The current maximum number of omissions is:',forget_max_cr[0],'[',','.join(forget_max_cr[1]),']')
    print('The maximum number of global omissions is:',forget_max_all[0],'[',','.join(forget_max_all[1]),']')


input()